task: FALCONBench_mcq_temploc_metaarch
doc_to_text: !function utils.FALCONbench_doc_to_text_mcq
doc_to_target: "gt_option"
generation_kwargs:
  max_new_tokens: 64
  temperature: 0
  do_sample: False
  question_format: "mcq"
  return_tempwindow: True
process_results: !function utils.FALCONbench_process_results_mcq_temploc
metric_list:
  - metric: acc
    aggregation: !function utils.FALCONbench_aggregate_results_mcq 
    higher_is_better: true
include: _default_template_yaml